//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderDetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> MenuItemID { get; set; }
        public int Quantity { get; set; }
        public decimal SubTotal { get; set; }
    
        public virtual MenuItems MenuItems { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
