//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservations()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ReservationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public System.TimeSpan ReservationTime { get; set; }
        public int NumberOfGuests { get; set; }
        public Nullable<int> TableNumber { get; set; }
        public string Status { get; set; }
        public string SpecialInstructions { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
